### ISSUE TITLE
Getting data but no sensors / entities created. 

### ISSUE THREAD

**Issue by tbrasser** [ben8p/home-assistant-bunq-balance-sensors#14]
Logs show:

```
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform

await asyncio.shield(task)

File "/config/custom_components/bunq/sensor.py", line 18, in async_setup_entry

sensors.append(BunqBalanceSensor(coordinator, account))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/bunq/bunq_balance_sensor.py", line 23, in __init__

self._async_update_attrs()

File "/config/custom_components/bunq/bunq_balance_sensor.py", line 47, in _async_update_attrs

self.entity_description.name = "bunq_" + account["description"].lower().replace(" ", "_")

^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "<string>", line 4, in __setattr__

dataclasses.FrozenInstanceError: cannot assign to field 'name'


```

**Comment by ben8p** [comment]
Hi,
I wonder if this could be because of an edge case on the account description (the name you see in the app).

If that is not too private, would you be able to share the name of your account ?

Maybe you use some special characters ? emojis ?

**Comment by tbrasser** [comment]
I don't think so, tried this and still no bueno:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor (documentation, issues)
First occurred: 18:10:17 (1 occurrences)
Last logged: 18:10:17

Error while setting up bunq platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bunq/sensor.py", line 18, in async_setup_entry
    sensors.append(BunqBalanceSensor(coordinator, account))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bunq/bunq_balance_sensor.py", line 24, in __init__
    self._async_update_attrs()
  File "/config/custom_components/bunq/bunq_balance_sensor.py", line 48, in _async_update_attrs
    self.entity_description.name = "bunq_".join(random.choices(string.ascii_letters + string.digits, k=4)).lower()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'name'

```

**Comment by sstolk90** [comment]
After the update from HA and maybe earlier from Bunq Update 24 I get this error too:
2024-01-07 10:42:46.146 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up bunq platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bunq/sensor.py", line 18, in async_setup_entry
    sensors.append(BunqBalanceSensor(coordinator, account))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bunq/bunq_balance_sensor.py", line 23, in __init__
    self._async_update_attrs()
  File "/config/custom_components/bunq/bunq_balance_sensor.py", line 47, in _async_update_attrs
    self.entity_description.name = "bunq_" + account["description"].lower().replace(" ", "_")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'name'

**Comment by ben8p** [comment]
Alright, I found the problem.
It has to do with a change in HA:
https://developers.home-assistant.io/blog/2023/12/11/entity-description-changes/

I'll work on a fix

**Comment by arner** [comment]
Ah, just seeing this now. See PR here: https://github.com/ben8p/home-assistant-bunq-balance-sensors/pull/15

**Comment by ben8p** [comment]
Brilliant!
It's merged. 
Thank you very much!

**Comment by sstolk90** [comment]
Works after update!

**Comment by ben8p** [comment]
Amazing! Thanks again @arner
