### ISSUE TITLE
Link account service erroring out

### ISSUE THREAD

**Issue by hendrer** [ben8p/home-assistant-bunq-balance-sensors#22]
Hi there - thanks for this integration, look forward to using it! Specifically, I am very interested in the link account service but it's constantly erroring out. Could you take a look please?

request - I masked the debit card number:

service: bunq.link_account
data:
  card_entity: sensor.mastercard_debit_nnnnnnn
  account_entity: sensor.bank_fees

error:
Failed to call service bunq.link_account. Invalid type for field "monetary_account_id" (expected INTEGER).

I've tried multiple accounts without success and all sensors are reporting values.

account_id: "nnnnnnn"
transactions:
    -
device_class: monetary
icon: mdi:cash-multiple
friendly_name: Bank Fees

**Comment by ben8p** [comment]
Hi,
Thanks for reporting.
I will check asap

**Comment by hendrer** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/bunq/bunq_api.py:279
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 3:42:28 PM (2 occurrences)
Last logged: 3:42:32 PM

[140543028381632] Error handling message: Unknown error (unknown_error) Hendre from 192.168.10.222 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 793, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bunq/services.py", line 91, in link_account_service
    await coordinator.bunq.link_account_to_card(card_id, account_id)
  File "/config/custom_components/bunq/bunq_api.py", line 279, in link_account_to_card
    del pin["id"]
        ~~~^^^^^^
KeyError: 'id'

**Comment by hendrer** [comment]
I also tried the transfer service and it also doesn't work. 

request:
service: bunq.transfer
data:
  from_account_entity: sensor.bank_fees
  to_account_entity: sensor.clothes
  amount: 1
  message: service test

error:
Failed to call service bunq.transfer. Request signature is required for this operation. For more information, visit the following documentation pages.

nothing in system logs

**Comment by ben8p** [comment]
Hi,
I pushed an update.
Can you confirm it fixes your issue ?

**Comment by hendrer** [comment]
Resolved, thank you!!!!

**Comment by hendrer** [comment]
Resolved, thanks
